name = "compass-board"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "COMPASS_BOARD_KV"
id = "0fe2ce6b322e438095f474121f588c4b"
preview_id = "00c285c018554872ab44bf8b34a711fc"
